const About = () => {
    return ( 
        <div className="about">
            <p className="about">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget gravida cum sociis natoque penatibus et magnis. Ultricies mi eget mauris pharetra. Sit amet venenatis urna cursus eget nunc scelerisque. Tincidunt nunc pulvinar sapien et ligula. Pellentesque elit eget gravida cum sociis natoque. Arcu bibendum at varius vel pharetra vel turpis. In egestas erat imperdiet sed euismod nisi porta lorem. Bibendum neque egestas congue quisque egestas diam. Nullam eget felis eget nunc lobortis mattis. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Id velit ut tortor pretium viverra suspendisse. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Sit amet venenatis urna cursus eget nunc scelerisque viverra. At tempor commodo ullamcorper a. Semper auctor neque vitae tempus quam pellentesque.

Adipiscing vitae proin sagittis nisl rhoncus. Euismod in pellentesque massa placerat duis ultricies lacus sed turpis. Pharetra vel turpis nunc eget. Id aliquet lectus proin nibh nisl condimentum id. In vitae turpis massa sed elementum tempus. Sit amet risus nullam eget felis. Porttitor rhoncus dolor purus non enim praesent. Elementum eu facilisis sed odio morbi. Tempor orci dapibus ultrices in. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Cras pulvinar mattis nunc sed blandit libero. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Eget nullam non nisi est sit amet. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. In vitae turpis massa sed elementum tempus egestas sed sed. Nullam ac tortor vitae purus faucibus. Lectus sit amet est placerat in egestas erat imperdiet sed. Nisi vitae suscipit tellus mauris a diam maecenas.

Ultricies mi quis hendrerit dolor magna. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus. Sem viverra aliquet eget sit amet tellus cras. Amet massa vitae tortor condimentum lacinia quis vel eros. Mauris cursus mattis molestie a iaculis. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Ac placerat vestibulum lectus mauris. Mauris a diam maecenas sed. Euismod in pellentesque massa placerat duis ultricies lacus sed. Massa id neque aliquam vestibulum morbi blandit cursus risus. Ac turpis egestas sed tempus. Euismod lacinia at quis risus sed vulputate. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Ac turpis egestas sed tempus. Netus et malesuada fames ac turpis egestas sed tempus urna.

Sed felis eget velit aliquet sagittis id consectetur. Elit pellentesque habitant morbi tristique senectus et netus et. Sed nisi lacus sed viverra tellus in hac habitasse. Vitae congue mauris rhoncus aenean vel elit scelerisque. Amet justo donec enim diam. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Lacus luctus accumsan tortor posuere ac ut consequat semper. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Viverra accumsan in nisl nisi scelerisque eu. In dictum non consectetur a erat nam. Amet cursus sit amet dictum sit amet. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Nunc id cursus metus aliquam eleifend mi in. Risus quis varius quam quisque. Purus sit amet luctus venenatis lectus magna fringilla urna. Sed id semper risus in. Arcu cursus vitae congue mauris rhoncus.

Bibendum enim facilisis gravida neque convallis a cras. Ornare lectus sit amet est placerat. Nunc mi ipsum faucibus vitae. Sit amet facilisis magna etiam tempor orci. Nisl tincidunt eget nullam non nisi est sit amet. Lacus viverra vitae congue eu consequat ac felis donec. Blandit turpis cursus in hac habitasse platea. Sapien pellentesque habitant morbi tristique senectus et netus et. Maecenas pharetra convallis posuere morbi leo urna. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Sed arcu non odio euismod lacinia at quis risus sed. Amet commodo nulla facilisi nullam vehicula ipsum a. Id diam maecenas ultricies mi eget mauris pharetra et. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Auctor elit sed vulputate mi sit amet mauris commodo quis. Porttitor leo a diam sollicitudin tempor id eu. Elit sed vulputate mi sit amet mauris commodo. Et malesuada fames ac turpis egestas integer eget aliquet nibh.
            </p>
        </div>
     );
}
 
export default About;